/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData vector = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skipprevious = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skipnext = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pauseicon = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
